name: Auto Merge Specific PRs

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    - cron: '0 0 */2 * *'  # 每2天0:00 UTC运行（北京时间8:00）
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List and Process Open PRs
        id: list-prs
        run: |
          # 获取所有开放的 PR
          gh pr list --state open --json number,title,mergeable,headRefName,author > prs.json
          echo "Raw PR list:"
          cat prs.json

          # 检查 prs.json 是否为空
          if [ ! -s prs.json ]; then
            echo "No PRs found."
            exit 0
          fi

          # 过滤标题匹配的 PR
          jq -r '.[] | select(.title | contains("本地模型-gemma3:27b-it-qat-自动化翻译") or contains("自动添加创意工坊地图")) | "\(.number) \(.title) \(.mergeable) \(.headRefName) \(.author.login)"' prs.json > filtered_prs.txt || {
            echo "Error filtering PRs with jq. Dumping prs.json for debugging:"
            cat prs.json
            exit 1
          }

          # 检查是否有匹配的 PR
          if [ ! -s filtered_prs.txt ]; then
            echo "No PRs with matching titles found."
            exit 0
          fi

          # 遍历匹配的 PR
          while read -r number title mergeable headRef author; do
            echo "Processing PR #$number: $title (mergeable: $mergeable, head: $headRef, author: $author)"

            # 处理 mergeable: UNKNOWN
            if [ "$mergeable" == "UNKNOWN" ]; then
              echo "PR #$number mergeable status is UNKNOWN, retrying..."
              for i in {1..3}; do
                sleep 10  # 等待10秒
                mergeable=$(gh pr view $number --json mergeable --jq '.mergeable')
                echo "Retry $i: mergeable status is $mergeable"
                if [ "$mergeable" == "MERGEABLE" ]; then
                  break
                fi
                if [ "$i" == "3" ] && [ "$mergeable" != "MERGEABLE" ]; then
                  echo "PR #$number still not mergeable after retries."
                  gh issue comment $number --body "Auto-merge failed: PR mergeable status is $mergeable after retries. Please check for conflicts or update the PR."
                  continue 2
                fi
              done
            fi

            if [ "$mergeable" != "MERGEABLE" ]; then
              echo "PR #$number is not mergeable (status: $mergeable), skipping..."
              gh issue comment $number --body "Auto-merge failed: PR is not mergeable (status: $mergeable). Please resolve conflicts or update the PR."
              continue
            fi

            # 更新 PR 分支
            echo "Updating PR #$number branch..."
            gh pr update-branch $number || echo "Failed to update branch, continuing..."

            # 检查 CI 状态
            echo "Checking CI status for PR #$number..."
            gh pr checks $number --watch --interval 30 --timeout 600 || {
              echo "CI checks failed for PR #$number."
              gh issue comment $number --body "Auto-merge failed: CI checks did not pass. Please check the CI pipeline."
              continue
            }

            # 检查是否需要批准
            echo "Checking if approval is needed for PR #$number..."
            required_reviews=$(gh api repos/UpKK-Xnet-YYDCS/UPKK_ZE_PUBLIC/branches/master/protection --jq '.required_pull_request_reviews.required_approving_review_count')
            if [ "$required_reviews" != "0" ] && [ "$author" != "github-actions[bot]" ]; then
              echo "Approving PR #$number..."
              gh pr review --approve $number || {
                echo "Failed to approve PR #$number."
                gh issue comment $number --body "Auto-merge failed: Unable to approve PR. Please ensure the PR author is not the same as the approver or disable required reviews."
                continue
              }
            else
              echo "Skipping approval for PR #$number (no reviews required or author is github-actions[bot])."
            fi

            # 尝试合并
            echo "Merging PR #$number..."
            if gh pr merge --merge $number; then
              echo "PR #$number merged successfully."
              gh issue comment $number --body "Auto-merge succeeded: PR merged into master."
            else
              echo "Failed to merge PR #$number."
              gh issue comment $number --body "Auto-merge failed: Unable to merge PR. Please check branch protection rules or conflicts."
            fi
          done < filtered_prs.txt
        env:
          GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}  # 使用 PAT
