name: Auto Merge Specific PRs

on:
  workflow_dispatch:  # 允许手动触发
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.title, '本地模型-gemma3:27b-it-qat-自动化翻译') ||
      contains(github.event.pull_request.title, '自动添加创意工坊地图')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if PR is mergeable
        id: check-mergeable
        run: |
          gh pr view "${{ github.event.pull_request.number }}" --json mergeable --jq '.mergeable' > mergeable.txt
          if [ "$(cat mergeable.txt)" != "MERGEABLE" ]; then
            echo "PR is not mergeable, exiting..."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Approve PR
        run: gh pr review --approve "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge PR
        run: gh pr merge --merge "${{ github.event.pull_request.number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
