name: Check Added Steam Workshop IDs

on:
  push:
    paths:
      - 'cs2/counterstrikesharp/configs/plugins/MapChooser/maps.txt'  # 当 maps.txt 文件发生变化时触发
  workflow_dispatch:  # 允许手动触发

jobs:
  check-workshop-ids:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Extract all Steam Workshop IDs
      id: extract_ids
      run: |
        grep -Pzo '"workshop_id"\s*"\K\d+(?=")' cs2/counterstrikesharp/configs/plugins/MapChooser/maps.txt > all_ids.txt

    - name: Run check script
      id: check_script
      run: |
        python scripts/check_workshop_ids.py cs2/counterstrikesharp/configs/plugins/MapChooser/maps.txt
      continue-on-error: true

    - name: Output result
      run: |
        if [ "${{ steps.check_script.outcome }}" == "failure" ]; then
          echo -e "\033[91mSome Steam Workshop IDs are unavailable.\033[0m"
          exit 1
        else
          echo -e "\033[92mAll Steam Workshop IDs are available.\033[0m"
        fi

    - name: Create Pull Request
      if: failure()  # 仅在上一步失败时触发
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: '禁用不可用的 Steam Workshop IDs'
        title: '禁用不可用的 Steam Workshop IDs'
        body: '部分 Steam Workshop IDs 不可用。请审核并确认禁用。'
        branch: 'disable-unavailable-ids'