name: Check Steam Workshop IDs

on:
  push:
    paths:
      - 'cs2/counterstrikesharp/configs/plugins/MapChooser/maps.txt'  # 当 maps.txt 文件发生变化时触发
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: '0 0 * * *'  # 每天午夜12点触发工作流

jobs:
  check-workshop-ids:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run check script
      id: check_script
      run: |
        python scripts/check_workshop_ids.py cs2/counterstrikesharp/configs/plugins/MapChooser/maps.txt
      continue-on-error: true

    - name: Output result
      run: |
        if [ "${{ steps.check_script.outcome }}" == "failure" ]; then
          echo -e "\033[91mSome Steam Workshop IDs are unavailable.\033[0m"
          exit 1
        else:
          echo -e "\033[92mAll Steam Workshop IDs are available.\033[0m"
        fi

    - name: Install GitHub CLI
      if: failure()  # 仅在上一步失败时触发
      run: |
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
        sudo apt-add-repository https://cli.github.com/packages
        sudo apt-get update
        sudo apt-get install gh -y

    - name: Authenticate GitHub CLI
      if: failure()  # 仅在上一步失败时触发
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Check for existing Pull Request
      if: failure()  # 仅在上一步失败时触发
      id: check_pr
      run: |
        gh pr list --repo ${{ github.repository }} --head disable-unavailable-ids --json number --jq '.[0].number' > pr_number.txt || echo "none" > pr_number.txt

    - name: Create or update Pull Request
      if: failure()  # 仅在上一步失败时触发
      run: |
        pr_number=$(cat pr_number.txt)
        if [ "$pr_number" == "none" ]; then
          gh pr create \
            --repo ${{ github.repository }} \
            --head disable-unavailable-ids \
            --base main \
            --title '禁用不可用的 Steam Workshop IDs' \
            --body '部分 Steam Workshop IDs 不可用。已将其对应的 enabled 字段从 1 改为 0。请审核并确认更改。'
        else
          gh pr comment $pr_number --body '部分 Steam Workshop IDs 不可用。已将其对应的 enabled 字段从 1 改为 0。请审核并确认更改。'
          gh pr ready-for-review $pr_number