name: Check Added Steam Workshop IDs

on:
  push:
    paths:
      - 'cs2/counterstrikesharp/configs/plugins/MapChooser/maps.txt'  # Runs on changes to the maps.txt file
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-workshop-ids:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Extract all Steam Workshop IDs
      id: extract_ids
      run: |
        # Assuming each line in maps.txt contains a Steam Workshop ID
        # Adjust the extraction method based on the actual format of maps.txt
        grep -Eo '\b\d{17}\b' cs2/counterstrikesharp/configs/plugins/MapChooser/maps.txt > all_ids.txt

    - name: Run check script
      id: check_script
      run: |
        python scripts/check_workshop_ids.py all_ids.txt
      # Ensure your Python script exits with a non-zero status if any ID is invalid

    - name: Output result
      run: |
        if [ "${{ steps.check_script.outcome }}" == "failure" ]; then
          echo -e "\033[91mSome Steam Workshop IDs are unavailable.\033[0m"
          exit 1
        else
          echo -e "\033[92mAll Steam Workshop IDs are available.\033[0m"
        fi

    - name: Create Pull Request
      if: failure()  # Trigger only if the previous steps failed
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: 'Disable unavailable Steam Workshop IDs'
        title: 'Disable unavailable Steam Workshop IDs'
        body: 'Some Steam Workshop IDs are unavailable. Please review and confirm disabling.'
        branch: 'disable-unavailable-ids'
