name: Check Workshop IDs in Collections

on:
  workflow_dispatch:

jobs:
  check_workshop:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run script to check workshop IDs
      id: check_workshop
      run: |
        file_path='cs2/counterstrikesharp/configs/plugins/MapChooser/maps.txt'
        collection_ids='3113843317'
        echo "Checking workshop IDs in collection $collection_ids using file $file_path"
        python scripts/check_workshop_in_collection.py $file_path $collection_ids

    - name: Read not found workshop IDs
      if: steps.check_workshop.outputs.result == 'failure'
      id: read_not_found
      run: |
        cat not_in_collections.txt
      continue-on-error: true

    - name: Check for existing issue
      id: issue_check
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: 'open',
            labels: 'bug',
          });
          const existingIssue = issues.find(issue => issue.title.includes('某些合集中未找到 Workshop ID'));
          if (existingIssue) {
            return { existingIssueNumber: existingIssue.number };
          } else {
            return { existingIssueNumber: null };
          }

    - name: Create or update issue
      if: steps.check_workshop.outputs.result == 'failure'
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const existingIssueNumber = ${{ steps.issue_check.outputs.existingIssueNumber }};
          const notFoundIds = await fs.promises.readFile('not_in_collections.txt', 'utf-8');
          const body = `在文件 cs2/counterstrikesharp/configs/plugins/MapChooser/maps.txt 中的某些 Workshop ID 未在指定的合集 3113843317 中找到。请检查并更新这些合集。\n\n未找到的 Workshop IDs:\n${notFoundIds}`;
          if (existingIssueNumber) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: existingIssueNumber,
              body: body,
            });
          } else {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '某些合集中未找到 Workshop ID',
              body: body,
              labels: ['bug'],
            });
          }