name: DownloadMapPreviewImagesMapPingJSON

on:
  workflow_dispatch:  # 仅允许手动触发

jobs:
  DownloadMapPreviewImagesMapPingJSON:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码库
      uses: actions/checkout@v3
      with:
        ref: master

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install requests pillow tqdm

    - name: 运行脚本
      id: check_script
      run: |
        python scripts/DownloadPreviewImagesByMappingJson.py cs2/counterstrikesharp/configs/plugins/MapChooser/MapPing.json

    - name: 压缩 map_previews_images 文件夹
      if: always()  # 即使脚本出错也执行此步骤
      run: |
        zip -r map_previews_images.zip map_previews_images
      working-directory: ./

    - name: 上传压缩文件作为 Artifact
      uses: actions/upload-artifact@v4.0.0
      with:
        name: map_previews_images
        path: map_previews_images.zip

    - name: 获取最新 Artifact 的 URL
      id: get_artifact_url
      run: |
        # 获取最新的 workflow run ID
        run_id=$(curl -s \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs" \
          | jq -r '.workflow_runs[0].id')
        
        # 获取最新 run 的 artifacts 列表
        artifact_id=$(curl -s \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/$run_id/artifacts" \
          | jq -r '.artifacts[] | select(.name=="map_previews_images") | .id')

        # 构造下载 URL
        artifact_url="https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$artifact_id/zip"
        
        echo "artifact_url=$artifact_url" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: 通知远程服务器下载和更新
      run: |
        curl -X POST -H "Content-Type: application/json" \
          -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36" \
          -d '{"artifact_url": "'"$artifact_url"'", "token": "${{ secrets.SECRET_TOKEN }}"}' \
          https://bbs.upkk.com/plugin.php?id=xnet_core_api:GithubAction_map_previews_images
