name: Validate JSON and JSONC files

on:
  push:
    paths:
      - 'cs2/counterstrikesharp/configs/map-text/**' # 监视此目录中的所有变化
      - 'cs2/entwatch/maps/**'
      - 'cs2/counterstrikesharp/configs/weapons_buyCommand/weapons.json' # 监视特定文件
      - 'cs2/cs2fixes/configs/zr/playerclass.jsonc'
  pull_request:
    paths:
      - 'cs2/counterstrikesharp/configs/map-text/**' # 监视此目录中的所有变化
      - 'cs2/entwatch/maps/**'
      - 'cs2/counterstrikesharp/configs/weapons_buyCommand/weapons.json'
      - 'cs2/cs2fixes/configs/zr/playerclass.jsonc'

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: List changed files
      id: list_changed_files
      run: |
        echo "Changed files:"
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt
        cat changed_files.txt

    - name: Install jsonlint-cli
      run: npm install -g jsonlint-cli

    - name: Validate JSON and JSONC files
      run: |
        echo "Validating JSON and JSONC files..."
        while IFS= read -r file; do
          if [[ $file == *.json || $file == *.jsonc ]]; then
            echo "Validating $file"
            if [[ $file == *.json ]]; then
              jq empty "$file" || exit 1
            elif [[ $file == *.jsonc ]]; then
              jsonlint-cli "$file" || exit 1
            fi
          fi
        done < changed_files.txt
